[package]
name = "autonomous-game"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
macroquad-tiled = "0.2.1"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5"
js-sys = "0.3.77"

[lib]
crate-type = ["cdylib", "rlib"]
