---
name: Build and Deploy WASM-Bindgen Vite React App
on:
  push:
    branches: [feat/wasm-bindgen]
  pull_request:
    branches: [feat/wasm-bindgen]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Vite React App
        run: cd frontend && npm run build
        env:
          NODE_ENV: production

      # Optional: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # The folder the action should deploy (output of Vite build)
          branch: gh-pages  # The branch the action should deploy to
